language: python
python:
  - "2.6"

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy python3-numpy python3-scipy

# command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"

# command to run tests
script: python -m nose2.__main__
