language: python

python: "2.7"

env:
    - TOXENV=py27
    - TOXENV=py32
    # - TOXENV=py33   # http://lists.alioth.debian.org/pipermail/debian-science-maintainers/2013-May/017973.html

branches:
  only:
    - master
    - develop

install:
    - sudo apt-get update -qq
    - pip install --quiet --use-mirrors tox
    - sudo apt-get install -qq python-numpy python3-numpy
    - sudo apt-get install -qq python-scipy python3-scipy

script: tox
