language: python

python "2.7"

env:
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33

branches:
  only:
    - master
    - develop

install:
    - sudo apt-get update -qq
    - pip install --quiet --use-mirrors tox
    - sudo apt-get install -qq python-numpy python3-numpy
    - sudo apt-get install -qq python-scipy python3-scipy

script: tox
